= Create the application
include::_attributes.adoc[]

== Creating a namespace to deploy our application

Create a folder for this exercise, we'll refer to it with: `${SPRING_BOOT_PROJECT}`

[source,bash,role="execute",subs="verbatim,attributes"]
----
cd ${SPRING_BOOT_PROJECT}
mkdir -p {app_name}
cd {app_name}
odo project create {username}-odo-{app_name}
----

== Deploying the database

[source,bash,role="execute",subs="verbatim,attributes"]
----
oc create -f ./k8s/postgresql-db.yaml -n {username}-odo-{app_name}
----

== Have a look to the catalog of components

[source,bash,role="execute",subs="verbatim,attributes"]
----
$ odo registry add AtarazanaRegistry https://github.com/atarazana/registry
New registry successfully added
----

[source,bash,role="execute",subs="verbatim,attributes"]
----
$ odo catalog list components
Odo Devfile Components:
NAME                           DESCRIPTION                                        REGISTRY
java-maven-atarazana           Upstream Maven and OpenJDK 11 - Atarazana          AtarazanaRegistry
java-openliberty-atarazana     Open Liberty microservice in Java - Atarazana      AtarazanaRegistry
java-quarkus-atarazana         Upstream Quarkus with Java+GraalVM - Atarazana     AtarazanaRegistry
java-springboot-atarazana      Spring Boot® using Java - Atarazana                AtarazanaRegistry
java-vertx-atarazana           Upstream Vert.x using Java - Atarazana             AtarazanaRegistry
nodejs-atarazana               Stack with NodeJS 12 - Atarazana                   AtarazanaRegistry
python-atarazana               Python Stack with Python 3.7 - Atarazana           AtarazanaRegistry
python-django-atarazana        Python3.7 with Django - Atarazana                  AtarazanaRegistry
java-maven                     Upstream Maven and OpenJDK 11                      DefaultDevfileRegistry
java-openliberty               Open Liberty microservice in Java                  DefaultDevfileRegistry
java-quarkus                   Upstream Quarkus with Java+GraalVM                 DefaultDevfileRegistry
java-springboot                Spring Boot® using Java                            DefaultDevfileRegistry
java-vertx                     Upstream Vert.x using Java                         DefaultDevfileRegistry
nodejs                         Stack with NodeJS 12                               DefaultDevfileRegistry
python                         Python Stack with Python 3.7                       DefaultDevfileRegistry
python-django                  Python3.7 with Django                              DefaultDevfileRegistry

Odo S2I Components:
NAME       PROJECT       TAGS                                                    SUPPORTED
java       openshift     latest,openjdk-11-el7,openjdk-11-ubi8,openjdk-8-el7     YES
nodejs     openshift     12-ubi8,latest                                          YES
dotnet     openshift     2.1-el7,2.1-ubi8,3.1-el7,3.1-ubi8,latest                NO
golang     openshift     1.13.4-ubi7,1.13.4-ubi8,latest                          NO
httpd      openshift     2.4-el7,2.4-el8,latest                                  NO
java       openshift     openjdk-8-ubi8                                          NO
nginx      openshift     1.14-el8,1.16-el7,1.16-el8,latest                       NO
nodejs     openshift     10-ubi7,10-ubi8,12-ubi7                                 NO
perl       openshift     5.26-el7,5.26-ubi8,5.30-el7,latest                      NO
php        openshift     7.2-ubi8,7.3-ubi7,7.3-ubi8,latest                       NO
python     openshift     2.7-ubi7,2.7-ubi8,3.6-ubi8,3.8-ubi7,3.8-ubi8,latest     NO
ruby       openshift     2.5-ubi7,2.5-ubi8,2.6-ubi7,2.6-ubi8,2.7-ubi7,latest     NO
----

We're goin go to use our `java-springboot-atarazana from Atarazana` devfile based component, as you can see we have two types of components `ODO Devfile components` and `Odo S2I Components`.

== Deploying the {backend_component_name} component

[source,bash,role="execute",subs="verbatim,attributes"]
----
mkdir -p Backend
cd Backend
odo create java-springboot-atarazana backend --starter --app {app_name}
odo config set --env JAVA_OPTIONS="-Dspring.profiles.active=openshift"
odo push
----

=== Testing the deployed service

[source,bash,role="execute",subs="verbatim,attributes"]
----
TEST_URL="http://$(oc get route --selector=app.kubernetes.io/instance={backend_component_name} -o jsonpath='{.items[*].spec.host}')"
curl ${TEST_URL}/hello && echo ""
----

== Testing locally with `local` profile

In this case we don't need connect to the PostgreSQL database we just deployed in OpenShift, we're going to use H2.

[source,bash,role="execute",subs="verbatim,attributes"]
----
mvn clean spring-boot:run -Dspring-boot.run.profiles=local -Plocal
----

=== Permissions needed

This needs to be run by a cluster-admin

[source,bash,role="execute",subs="verbatim,attributes"]
----
oc adm policy add-scc-to-user privileged -z default -n {username}-odo-{app_name}
oc adm policy add-scc-to-user anyuid -z default -n {username}-odo-{app_name}
----

=== Debugging locally the {backend_component_name} with `telepresence`

Telepresence will...

[source,bash,role="execute",subs="verbatim,attributes"]
----
export TELEPRESENCE_USE_OCP_IMAGE=NO

ODO_COMPONENT_NAME=$(yq r .odo/env/env.yaml ComponentSettings.Name)

telepresence --swap-deployment $(oc get deploy --selector=app.kubernetes.io/instance=${ODO_COMPONENT_NAME} -o jsonpath='{.items[*].metadata.name}') --expose 8080
----

== Testing locally with `openshift` profile

In this case we don't need connect to the PostgreSQL database we just deployed in OpenShift, we're going to use H2.

[source,bash,role="execute",subs="verbatim,attributes"]
----
DEPLOYMENTCONFIG_POSTGRESQL_USER=luke DEPLOYMENTCONFIG_POSTGRESQL_PASSWORD=secret mvn clean spring-boot:run -Dspring-boot.run.profiles=openshift -Popenshift
----

psql -U $POSTGRESQL_USER $POSTGRESQL_DATABASE -c 'select * from FRUIT;'