---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-POSTGRESQL_USER: '{.data[''POSTGRESQL_USER'']}'
    template.openshift.io/expose-POSTGRESQL_PASSWORD: '{.data[''POSTGRESQL_PASSWORD'']}'
    template.openshift.io/expose-POSTGRESQL_DATABASE: '{.data[''POSTGRESQL_DATABASE'']}'
    #service.binding/POSTGRESQL_USER: 'path={.data.POSTGRESQL_USER}' 
    #service.binding/POSTGRESQL_PASSWORD: 'path={.data.POSTGRESQL_PASSWORD}' #annotate here.
    #service.binding/POSTGRESQL_DATABASE: 'path={.data.POSTGRESQL_DATABASE}' #annotate here.
  labels:
    template: postgresql-persistent-template
  name: my-database
stringData:
  POSTGRESQL_USER: luke
  POSTGRESQL_PASSWORD: secret
  POSTGRESQL_DATABASE: my_data
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  labels:
    app: my-database
    template: postgresql-persistent-template
  name: my-database
spec:
  ports:
  - name: postgresql
    nodePort: 0
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: my-database
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: my-database
    app.kubernetes.io/component: my-database
    app.kubernetes.io/instance: my-database
    app.kubernetes.io/part-of: spring-boot-app
    #app.openshift.io/runtime: postgresql
    app.kubernetes.io/name: postgresql
    template: postgresql-persistent-template
  name: my-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
    service.binding/DB_CREDS: 'path={.spec.selector.name},objectType=Secret' 
  labels:
    app: my-database
    app.kubernetes.io/component: my-database
    app.kubernetes.io/instance: my-database
    app.kubernetes.io/part-of: spring-boot-app
    #app.openshift.io/runtime: postgresql
    app.kubernetes.io/name: postgresql
    template: postgresql-persistent-template
  name: my-database
spec:
  replicas: 1
  selector:
    name: my-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: my-database
    spec:
      containers:
      - capabilities: {}
        envFrom:
        - secretRef:
            name: my-database
        image: ' '
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: my-database-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: my-database-data
        persistentVolumeClaim:
          claimName: my-database
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgresql
      from:
        kind: ImageStreamTag
        name: postgresql:10-el8
        namespace: openshift
      lastTriggeredImage: ""
    type: ImageChange
  - type: ConfigChange
---
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: backend-servicebinding
spec:
  application:
    group: apps
    resource: deployments
    name: backend
    version: v1
  services:
    - group: apps.openshift.io
      version: v1
      kind: DeploymentConfig
      name: my-database
      id: database